 1. The 'Mona Lisa' is currently the     most valuable painting in the world.
TRUE... it's worth $100 million
 2. The largest single museum in the     world is located in Russia.
FALSE... the American Museum of Natural  History is in New York City
 3. The largest art gallery in the world is located in the United States.
FALSE... the Winter Palace & Hermitage   in Leningrad, USSR
 4. More people speak 'English' than     any other language in the world.
FALSE... 695 million people speak        'Mandarin' in Northern China
 5. There are 120,000 words in the       English language.
FALSE... 490,000 words + 300,000         technical terms
 6. The Bible is the world's all-time    best selling copyright book.
TRUE...  and the Guinness Book of World  Records is second
 7. $1 million is the greatest advance   royalty paid for any book.
FALSE... James Clavell was advanced $5   million for 'Whirlwind'
 8. Dorothy Straight was the youngest    author (commercially published book).
TRUE... she wrote 'How the World Began'  at the age of 4
 9. Charles Schultz's 'Peanuts' was the  longest lasting comic strip.
FALSE... Rudolph Dirks' 'Katzenjammer    Kids' still holds the record
10. Charles Schultz's 'Peanuts' had the  largest syndication.
TRUE
11. The largest library in the world is  located in England.
FALSE... the Library of Congress is in   Washington, D.C.
12. $332,800 is the highest price ever   paid for a single page of advertising.
TRUE... for the back cover of Parade     Magazine
13. An organ is the largest and loudest  musical instrument in the world.
TRUE... the 'Auditorium Organ' is        located in Atlantic City, N.J.
14. The most difficult musical           instrument is the French Horn.
TRUE... the Ukelele is the easiest,      according to the experts
15. Michael Jackson was paid the highest amount at one location while on tour.
FALSE... Bruce Springsteen in '84, $117  million, 4 nights at L.A. Colesium
16. The largest opera house in the world is located in the United States.
TRUE... Metropolitan Opera House,        Lincoln Center, New York City
17. Songs written by Paul McCartney sold the most single records.
TRUE... 43 of his songs sold at least 1  million records
18. The largest theater stage in the world is in the United States.
TRUE... Ziegfeld Room, Bally Grand in    Reno, Nevada
19. Actor Red Skeleton has the longest   run of one-man shows.
FALSE... Victor Borge, 849 shows of      Comedy in Music (1953 to 1956)
20. Singer Dolly Pardon received the     highest pay for a single performance.
TRUE... she earned $400,000 for a single concert
21. Paul Harvey is the most heard        broadcaster on radio in the world.
FALSE... Larry King broadcasts to 272    stations in all 50 states
22. Kenny Rogers received the highest    pay for a single taping of TV.
TRUE... $2 million from HBO in 1983
23. Tom Selleck's $220,000/Magnum P.I.   set the record for T.V. performers.
FALSE... Carroll O'Connor earned         $275,000 for each Archie Bunker's show
24. Actor Marlon Brando received the     highest pay in cinema history.
FALSE... Sylvester Stallone received $12 million for Rocky IV
