 1. Boxing with gloves took place in     Greece as far back as 1520 BC.
TRUE
 2. The Queensberry Rules of Boxing      were formulated in Scotland in 1867.
FALSE... in England
 3. The greatest recorded number of      rounds of boxing was 136.
FALSE... 276 rounds took 4 1/2 hours     (England, 1825)
 4. The longest recorded fight with      gloves lasted 110 rounds.
TRUE...  it took 7 1/3 hours
 5. The longest world title fight        lasted 18 rounds.
FALSE... 42 rounds, Joe Gans (USA) beat  Battling Nelson (Denmark), 1906
 6. The record for the shortest          professional bout is 7 seconds.
TRUE... Al Carr stopped Lew Massey (New Haven, Conn., 1936)
 7. The tallest world heavyweight        champion was Primo Carnera.
TRUE... he was 6' 8.5" (1933)
 8. The heaviest world heavyweight       champion was George Forman.
FALSE... Primo Carnera (Italy), 267      pounds (1933)
 9. Muhammad Ali held the longest reign  as the world heavyweight champion.
FALSE... Joe Louis, 11 years/252 days    (1937-49)
10. Greg Page held the shortest reign    as the world heavyweight champion.
TRUE... 150 days (1984-85)
11. The youngest man to win the          heavyweight crown was Michael Spinks.
FALSE... Floyd Patterson, 21 years,      331 days (1956)
12. The oldest man to win the            heavyweight crown was Archie Moore.
FALSE... Jersey Joe Walcott, 37 years,   5 months/18 days (1951)
13. Heavyweight champion Mike Tyson has  the most consecutive KO's.
TRUE... 26 KO's (1984-87)
14. Larry Holmes is the only undefeated  heavyweight champion.
FALSE... Rocky Marciano, 49 wins (43 by  KO), no losses or draws (1947-56)
15. Heavyweight George Forman had the    highest career knockout percentage.
TRUE... 89.36%, 42 out of 47 bouts       (1967-74)
16. Rocky Grazziano had the most title   bouts in his career.
FALSE... Jack Britton, 37 bouts as a 3-  time welterweight champ (1915-22)
17. Henry Armstrong is the only man to   hold 3 world titles simultaneously.
TRUE... featherweight, lightweight,      welterweight (Aug-Dec, 1938)
18. Archie Moore had the greatest number of knockouts in a career.
TRUE... 145 knockouts (1936-63)
19. Gene Tunney lived the longest of     any heavyweight.
FALSE... Jack Dempsey, 87 years/341 days (1896-1983)
20. Joe Louis had the greatest number    of consecutive KO's at any weight.
FALSE... Lamar Clark (USA), 44           consecutive knockouts (1960)
21. Bobby Dobbs has the greatest         recorded number of fights in a career.
TRUE... 1,024 fights (1875-1914)
22. Harry Grebb holds the record for the most fights without a loss.
FALSE... Packey McFarland, 97 fights     without a defeat (1905-15)
23. Muhammad Ali had the highest         earnings in his boxing career.
TRUE... $69 million, 61 heavyweight      fights (Oct 1960-Dec 1981)
24. Sugar Ray Leonard had the greatest   purse for one boxer.
TRUE... $12 million, world-welterweight  title vs. Thomas Hearns (1981)
