 1. Malificent was the evil witch in     Sleeping Beauty.
TRUE
 2. One of the Seven Dwarfs in Snow      White was called droopy.
FALSE... Doc, Sleepy, Happy, Dopey,              Grumpy, Sneezy, Bashful
 3. Bambi's rabbit friend was called     Dumper.
FALSE... Thumper
 4. In Dumbo, doves sing, 'When I See    an Elephant Fly.'
FALSE... 'crows' sing this song
 5. The magic words in Cinderella are    'Supercalifragilistic-expialidocious.'
FALSE... 'Bibbidi-Bobbidi-Boo'
 6. Mickey Mouse stars in a segment of   Fantasia called Sorcerer's Apprentice.
TRUE
 7. Henry Mancini conducted the          orchestra for Fantasia.
FALSE... Leopold Stokowski
 8. Donald Duck's three nephews were     called Huey, Dewey and Louie.
TRUE
 9. 'Bibbidi-Bobbidi-Boo' is THE WORD    in Mary Poppins.
FALSE... 'Supercalifragilistic-          expialidocious'
10. Peter Pan lived in Never-Never Land
TRUE
11. Captain Hook lost his hand to a      whale
FALSE... to an alligator
12. Winnie-the-Pooh's striped friend     was named 'Tigger.'
TRUE
13. Davy Crockett come from Kentucky.
FALSE... Tennessee
14. Peter Pan's shadow was hidden in a   dresser drawer?
TRUE
15. Merryweather was the last of the     good fairies to bestow her gift to      Sleeping Beauty.
TRUE
16. Mickey & his gang rescue 'Sleeping   Beauty' from the Giant in...            'Mickey & the Beanstalk.'
FALSE... they rescued a golden harp
17. Bedknobs and Broomsticks takes place during World War I.
FALSE... World War II
18. In Alice in Wonderland, the walrus   dines on oysters.
TRUE
19. Jiminy Cricket's favorite song is    'Somewhere, over the Rainbow.'
FALSE... 'When I wish upon a star...'
20. Donald Duck's wealthy uncle is       called 'Scrooge McDuck.'
TRUE
21. Disney's 1st full-length, animated,  musical was 'Snow White and the         Seven Dwarfs.'
TRUE
22. Paris was the setting for '101       Dalmatians.'
FALSE... it took place in London
23. When Tramp took Lady out to dinner,  they had Spaghetti.
TRUE
24. Pinocchio's father's name was        Geppetto.
TRUE
