 1. The earliest records of horseback    riding date back to about 1400 BC.
TRUE...  in Assyria and Egypt
 2. The first racing on horseback was by the Greeks in 648 BC.
TRUE...  at the 33rd Olympic Games
 3. Pari-mutuel betting was developed    by an American in 1935.
FALSE... by Frenchman Pierre Oller in    late 1800's
 4. More people attend horse races in the U.S.A. than any other type of        sports event.
TRUE
 5. Man-o'War was the most famous        American race horse, winning 20 of 21   races.
TRUE
 6. Citation was the first horse to win  the Triple Crown.
FALSE... Sir Barton (1919)
 7. Citation was the first horse to win  $1 million.
TRUE... in 1948
 8. Affirmed was the first horse to win  more than $2 million.
TRUE... in 1978
 9. The most won in a single race is     $2.6 million by 'Spend-a-Buck'.
TRUE... in 1985
10. The greatest amount ever won by a    horse was by 'Secretariat' (1972-73).
FALSE...  'John Henry' won over $6.5     million (1977-85)
11. Ten horses have won the triple crown since Sir Barton's win in 1919.
TRUE...  'Seattle Slew' (1977) and       'Affirmed' (1978) are the latest
12. Jockey Laffitt Pincay has won the    most horse races.
FALSE... Willie Shoemaker won over 8000  races, Pincay won over 6000 races
13. Shoemaker was the first jockey to    earn more than $12 million in 1 year.
FALSE...  Chris McCarron (USA) earned    that amount in 1984
14. In a harness race, the two-wheeled   carriage is called a sultry.
FALSE... a sulky
15. A thoroughbred horse can be traced   back to 1 of 3 Arabian stallions.
TRUE... 'Darley Arabian', 'Byerley Turk' and 'Godolphin Barb'
16. Arabian horses are best known for    their stamina.
FALSE... for their speed
17. Thoroughbreds are allowed to race    when they are 1 year old.
FALSE... 2 years old
18. A newborn thoroughbred is called a   yearling.
FALSE... a foal
19. One year old thoroughbreds are       called foals.
FALSE... yearlings
20. Two year old male thoroughbreds are  called colts.
TRUE
21. Two year old female thoroughbreds    are called fillies.
TRUE
22. Five year old male thoroughbreds     are called stallions.
FALSE... horses
23. Five year old female thoroughbreds   are called mares.
TRUE
24. A furlong is 1/2 of a mile.
FALSE... 1/8 of a mile
