3000 X=30:ID$="Chapitre 1":IN$="Traduisez en francais...":RETURN
3010 DATA l'affiche,the poster,le cahier,the notebook,la classe,the class,la corbeille,the wastebasket
3020 DATA le crayon,the pencil,"l'eleve",the student,"la fenetre",the window,la gomme,the eraser,le livre,the book
3030 DATA madame,madam,mademoiselle,miss,monsieur,mister,le papier,the paper,la porte,the door,le professeur,the teacher
3040 DATA la salle de classe,the classroom,le stylo,the pen,le la les,the,bien,well,"tres",very
3050 DATA et,and,au revoir,goodbye,bonjour,hello,c'est,it is,merci,thank you,oui,yes,non,no,voici,here is,"voila",there is,pas mal,not bad
 
