WTIME.DO
--------

This is a spreadsheet that calculates times around the world in 24 hour clock format based on the Greenwich Mean Time (GMT) entry at the top of the sheet. For the uninformed, GMT is the time at any point on the Greenwich Meridian - an imaginary line running directly from the North to the South Pole through Greenwich (East of London, England).

The first column contains the place name and the second is the country. The third column gives the time difference from GMT in hours. The fourth column lists local standard time. The fifth column can be ignored, as it holds an extra formula which is necessary where time differences contain half hours.

GMT should be entered as hours and minutes only, separated by a decimal point. For example, 8pm would be entered as 20.00 or just 20 and 7:19am would be entered as 7.19 (note use of 24 hour format).

The spreadsheet is in SYLK format, so that it can be loaded into both the Model 200's Multiplan or Microsoft Excel on a PC. I assume it would work with Multiplan ROM on a Model 100/102, but it hasn't been tested.

Extra times can be added, but be sure to copy the appropriate formula(e). For positive time differences of whole hours: use the formula contained in R6C4 (D6). For positive time differences with half hours: use the formulae contained in R5C4:5 (D5 and E5). For negative time differences of whole hours: use the formula contained in R15C4 (D15). For negative time differences with half hours: use the formulae contained in R51C4:5 (D51 and E51).

Are there any other current Model 100/200 users out there?!

Alastair Wiggins
7th June 1995
[100270,403]
