A soft green fuzz
An angry engineer
A very large memory bank
The harvest moon
All the money in the world
A small little man
The Empire State Building
A philosophy professor
A secret computer
The smallest farm in Iowa
The oldest man alive
The Democratic party
An elephant
A book on card games
A warehouse full of boxes
A deranged lumberjack
A young computer programmer
The London Symphony Orchrestra
Darth Vader
A gaggle of geese
An automatic car wash
Three tons of yogurt
The United States Senate
A four-star general
