puts money in the bank
wears a bikini
takes the train to Vermont
dies of starvation
reads magazines
puts money in the bank
eats the neighbors hedge
runs the New York Marathon
murders the president
gets wet in the rain
finds a lost treasure
rides off into the sunset
whistles to a pretty girl
steals one million dollars
empties the trash can
falls into a well
takes off in a space ship
joins the French Foreign Legion
eats dog food
trips over a log
crawls to the nearest telephone
escapes from jail
flies off into the wide blue yonder
bites the big one
cries "Wolf"
wins the Irish Sweepstakes
is up a creek without a paddle
gets a job with the Peace Corps
goes where no man has gone before
had a great adventure
went on an island cruise
