AO 53 already open
BN 51 bad file number
BS  9 bad subscript
CF 58 file not open
CN 17 can't continue
DD 10 doubly dimensioned array
DS 56 direct statement in file
EF 54 input past end of file
FC  5 illegal function call
FF 52 file not found
FL 57 undefined error
ID 12 illegal direct
IE 50 undefined error
IO 18 error
LS 15 string too long
MO 22 missing operand
NF  1 NEXT without FOR
NM 55 bad file name
NR 19 no RESUME
OD  4 out of data
OM  7 out of memory
OS 14 out of string space
OV  6 overflow
RG  3 RETURN without GOSUB
RW 20 RESUME without error
SN  2 syntax error
ST 16 string formula too complex
TM 13 type mismatch
UE 21,23-49,
   59-255 undefined error
UL  8 undefined line

