Captured message thread on the subject of joysticks for the Model 100.

#: 139033 S8/Tech/Programming
    20-Jan-87  03:23:36
Sb: #Joystik 4 M100/102?
Fm: Cris Agnew 72245,731
To: All

Is it possible to construct a joystik for the M100/102 using one of the
interface ports?

The grounding of the pin 8 and 2 on the modem port changes the status flag
which raise the possiblity of constructing a joystik using this method (only
if there are 5 or 6 ports that can be tested for the status change when one of
the pins is gounded).

Maybe this idea is far-fetched but it is probably worth exploring. It may help
compensate which the M100/102 lacks.


Fm: Tony Anderson 76703,4062

I don't think you have sufficient port inputs that can be tested that way to
be able to implement a joystick... or mouse, for that matter.  The ring detect
status flag you mention changes only one bit in the port, so you have either
an on or off detect capability.  For a joystick, you need to be able to detect
"proportional position", which would require defining an entire byte, so that
you could define 256 positions of the stick in each direction.

One might be made with internal electronics, that could be attached to the
RS-232 port, or the system buss, but it would be a major project.  As I
recall, there are several unused I/O ports, and a system buss device could
grab hold of, and use a couple of them.

It's also possible such a device could be made to use the entire modem port,
acting as another modem, with a running program monitoring the modem for
input.

If you build one, be sure to give us the details, as it would open up a whole
new area of programming; as we could develop a mouse technique for the
portables, along with mouse programs, etc...


Fm: Cris Agnew 72245,731

Thanks for some tips. I'm doing some brainstorming on this right now.

No problem, I'll keep you and others informed on this. Sure, it will be a
milestone for the M100/102. I wished that Tandy had thought about it before
they upgraded the  M102 or designed a seperate compacted, yet portable unit to
interface with the system bus or RS232 and the mouse. (I prefer mouse over
joystik.)


Fm: Eiji Miura 76703,4311

Tony,

Didn't we used to see advertisement for a joystick or mouse (I forgot which
one) for the M100?  I think it was in Portable 100.

I think you have all backissues of Portable 100.  Swindell Judy, Inc.
advertised "SJI Magic Mouse" for Model 100.  Their first ad. appeared in
September, 1984 issue of Portable 100, and it ran every month up to February,
1985 issue.

I wonder if anybody ever bought this product...


Fm: Tony Anderson 76703,4062

Eiji,

I don't know.  It would be worth looking into.  But Swindell Judy is now out
of business.  Seems Bill Templeton had some contact with them, though.


Fm: Mark Lutton 73106,1627

Cris -

An Atari-style joystick (just a few discrete positions, not proportional)
would be easier than an IBM/Apple style.  A possibility would be one that uses
the bar code reader port and contains enough sophisticated stuff to send a
coded message giving its position.  It would certainly be a handy thing to
have -- and could possibly even use existing bar-code software if it used a
code that looked like bar code -but it probably would be expensive and tedious
to build.


Fm: Cris Agnew 72245,731

The concept of using the bar-code port is a bit too complicated and as you
said, expensive. Not many user have a bar-code reader for several reason. I
dont have one because the cost is out of question. Second, the use for it is -
in my opinion, nothing (I'm speaking for myself..no offense.)

If someone can afford it and has some use for it - then it is reasonable for
them.

I'm trying to keep something reasonable so everybody can have one without much
to consider because of some restrictions or limitations.

Thanx for the suggestion. (This is not to discourage you or others from
trying, if you think it will work, it would work. Everybody have ways of
getting around the impossibles.)


Fm: Philip Caracena 76656,1060

Guys- Ultrasoft advertizes a Joystick
in the back of their Disk Power manual.
"A joystick interface for the 100/102/
200" Plus a disk full of games for it!
$49.95 and it will save you lots of
time.  I don't have it so have no idea
on details.


Fm: Tony Anderson 76703,4062

Yes, I found it.  Will contact them, and see if I can get a review sample.  Oh
Joy!  A Joystick! Can a mouse be far behind?


Fm: Mark Lutton 73106,1627

By merest coincidence, Steve Cremer talked about connecting a joystick at
today's Boston Computer Society Laptop User Group meeting. He uses an Atari
style joystick -- four switches, one for each direction. He wired it to the
cursor keys.  There are two contacts for each key; one of them is ground.  You
wire each of the other contacts to one switch in the stick.  Pushing the stick
to the left is now the same as hitting the cursor left key; holding it to the
left is the same as holding the key (automatic repeat).  All the games that
use the cursor control keys now work with the joystick. You can disconnect the
bar code reader port from the motherboard and wire the cursor control keys to
the proper pins on the port. I think the standard Atari joystick plug plugs
right in.

NOTE: File has been uploaded to DL1 under the name BCSLAP.871

