instruction to the program Grfx.ba.
 
the program starts by asking you the
file name.  if there isn't a file by
that name, it opens one.
it then asks "print x,y?".  that will
print the x,y coordinates of the cursor
in the lower left corner.  answer that
with a capital "y".
It then asks "Print file?".  trying to
print a file that has nothing in it
will give you a error message.
i suggest you start with one of the "g"
files.  (g1.do g2.do ...)
The cursor start in the top left corner
so don't hit an up or left arrow 'cause
that will give you an error
 
the following function keys.
	f1) set dot
	f2) draw line
	f3) draw box
	f4) draw box filled
	f5) erase box.
	f6) draw circle
	f7) ----
	f8) ----
the key functions are as follows:
<esc> end program & condense grfx file.
    try not to break out the program
    just to end it.  although no harm
    is done if you've <enter>ed your
    function and then 'break'ed.  just
    restart the program.
<1> set x1,y1
<2> set x2,y2
<w> this reprints the file and waits
    after each line is drawn until a
    key is pressed
<s> Change set points.  to move the
    image up, down, left, or right.
    this value adds to the files'
    x,y numbers.  this is not a
    permanet change!
<c> Change permanetly the setpoints in
    the file to what is on the screen.
<tab> redraws your file
<enter> enters the last "f" function
    into your file.
 
you use the arrows to move the 'dot'
cursor to set your x1,y1 & x2,y2 points
 
move the cursor to say, 10,10, press 1
move cursor left & down;  press 2
pressing 'f2' will draw a line between
the two points.  'f3' will draw a box
using these two points. press <enter>
and the last function will be saved to
the file. a low tone indicates that
and error was made and the function
wasn't saved. a 'beep' means o.k.
 
'g#'files can be edited with the text
editor.  using the <w> function will
tell you the line # a certain function
is on.
 
if there are any questions, please
use 'email'.  i'm only on the sig every
few days.
  Russ villanueva. [70526,1434].
  happy drawing.

