1 'MESSAGE.SRL by JAMES YI/73328,1653
2 ONERRORGOTO100
5 L$="Hello.  Press any key to display your message.":GOTO70
10 CLS:PRINTCHR$(27)+"p":PRINT@80,STRING$(41," ")SPACE$(38)STRING$(41," "):PRINTCHR$(27)+"q" 
20 L$=RIGHT$(L$,L-1)+LEFT$(L$,1)
30 IF INKEY$<>""THEN60
40 PRINT@121,LEFT$(L$,38)
50 GOTO20
60 PRINT:INPUT"message";L$
70 L=LEN(L$):IFL<38THENL$=L$+SPACE$(38-L)
75 L$=L$+SPACE$(8)
80 L=LEN(L$)
90 GOTO10
100 PRINT"LINE TOO LONG.  129 CHRS MAX.":RESUME60

