Lacking any specific information on the A&J System 100 Wafer drive currently
being advertised for the Model 100, I have archived these recent threads from
the message board.


Sb: #A&J SYSTEM 100
Fm: JAMES HOWELL 72757,2716
To: ALL

IF YOU HAVE ANY QUESTIONS ABOUT THE A&J SYSTEM 100 LEAVE A MESSAGE FOR JIM
HOWE SINCERELY JIM HOWELL


Fm: Stephane Burgoyne 72747,1205

Has anybody tried this new product? If so, any feedback to give on it? Is the
unit ONLY menu-driven, or can it be controlled from a BASIC file?? Is there a
M/L operating system? Any comments would help. Thanks


Fm: Asysop Tony Anderson 70506,1261
To: Stephane Burgoyne 72747,1205 (X)

A couple of the SIG members have purchased the A/J Micro drive, and have
indicated in messages that they are satisfied with it.  One of them may see
your message and respond.

However, the unit is relatively new as a model 100 peripheral, and is not yet
supported here, since we have no information on them, nor units to explore and
play around with.

Wafer technology is based on the Exatron Stringy Floppy, originally designed
for the Radio Shack model 1, back in the mid 70's.  Wafers are comparatively
expensive, $4 to $6 each, I believe.  Someone made a comment that you could
only store 8 files on a wafer.

Apparently, A/J will support the product via it's own Bulletin Board System,
which you gain access to after purchasing the unit.

Good Luck.


Fm: Bill Templeton 75655,1056

One of our members brought a new A&J Micro Drive to our meeting last Sunday
afternoon, and it is smaller than the TDD, and uses very small wafer tapes
(slightly different than those used by Holmes' Bullet which several of us used
before the Chipmunk was introduced).  The drive looks very nice and is priced
at less than half the TDD, but this tape media stretches (especially the
longer tapes 50'+) after using it awhile, and there is only ONE, single source
manufacturer, of these wafers (ENTEPRO, Sunnyvale,CA).  If you would like to
call this member, I will EMail his phone number to you here in the S.F. Bay
Area, and he would be happy to tell you the details regarding its operation. 
Several members tried to talk him into buying the TDD, as the Chipmunk was out
of his price range, but he bought the A&J Micro Drive and seems to be happy...
And everyone thinks Don is a genius when it comes to solving problems, so that
old saying must be true... "Different strokes for different folks!"...


Fm: JAMES HOWELL 72757,2716

TO ALL MODEL 100 OWNERS AND OTHERS INTERESTED IN THE MASS STORAGE SYSTEM
MANUFACTURED BY A&J MICRO DRIVE SHOULD LEAVE MESSAGES WITH THE TOPIC OF "A&J
SYSTEM 100". THIS WILL HELP ME FIND YOUR QUESTIONS.   JAMES HOWELL 72757,2716


Fm: KENNETH WOOD 72226,3555

I HAVE PURCHASED THE A&J MICRO DRIVE AND USE IT AS A PORTABLE PARTNER WITH MY
RS DVI.  IT IS VERY DEPENDABLE
   AND RUGGED THE COST IS SO SMALL I FELT I COULDN'T AFFORD NOT TO GIVE A TRY
FOR MY NEED OF PORTABLE STORAGE.  WOW! IT'S GREAT
                  I LOVE IT
                  KEN


Fm: Robert R. Smith, Jr. 72116,1374

Jim: How about a rundown on how the A&J works, comparing it to the Tandy Disk
D rive but your literature doesn't address its operating limitations and
advantag s.


Fm: KENNETH WOOD 72226,3555

    If you load TMPC and save it to Ram
 at its proper address and then clear 150,57344 and load the SYSTEM for your
A&J Micro Drive and call 57344
 you then can go to Basic and LOADM "TMPC" and then SAVEM"A:TMPC",XXXXX
,XXXXX,XXXXX.   (X)=numbers for correct address.
                      ken


Fm: Mike White 71046,653

Does anyone have any experience with the A & J System 100 wafer tape drive for
the M100? I can't seem to find anything on it in the DL. It seems like a good
way to go for off-line storage. What's the catch?


Fm: Asysop Tony Anderson 70506,1261

See the current information on the wafer drive from A&J with the command,
RS;S;A&J;0.  That'll give you the benefit of the latest comments on the unit.

There is nothing in the database on this product.

The "catch", in my opinion, is that it's based on 10 year old technology, and
uses non-standard, over-priced, "wafers".  But then, who am I ??? If that's
what your budget will allow, go for it.  I think you'd be better off with the
Tandy Portable Disk Drive, myself... but then again, Who am I ???


