001,Entrance Hall
   You are at the west end of a long
hall. To the north and south are doors.
To the east is a long hallway.
-
2,3,20,-5,0,0,0,0,0,-5
There is an altar there!
PRAY,2,2
,,0,0
ALTAR
The altar is a statue of an eagle.
HALL
The hall goes ever on and on...




2
The eagle is a bird of prey(sic)!
There is an altar in the west wall.
<<< SCRAPE! >>> ---The west wall slides up into the ceiling.
To the west is a low, rough hewn passageheading down.
=
005,Crossroads
   You are in a room with passages
leading north, south, east and west.
The north passage leads upward, the eastpassage is narrow and has a sign paintedin red on the floor, and the west
passage is very dusty.
+
   The south passage is very wide and
tall, and has a parquette floor. Above  you hanging from the ceiling is a very
large and decrepit crystal chandelier.
-
1,6,40,19,-10,0,0,0,1,0

PULL CORD,2,2
,,0,0
CHANDELIER
You see a red cord hanging from the     center of the chandelier.
SIGN
The sign on the floor is painted with   blood!


SIGN
To the east is the mapmaker's delight!
4
Where there is a light, there must be a light switch.
The chandelier is unlit.
The chandelier lights up!  The flames   burn with an eerie red color.
In the chandelier's eerie red glow you  see a low passageway to the northeast.
=
002,Temple
   Painted on the north wall is some
sort of unusual design.
-
0,-1,0,-30,0,0,0,0,0,0
There's no door there.
SAY HOLY MACKEREL,2,2
WAND,magic wand,10,0
DESIGN
It is some kind of fish, but because thewall is pitted, there are holes in it.
FISH
It appears to be a mackerel.




3
The fish is a mackerel, and it's holey.
A voice says: "You must name the design on the north wall!"  There appears to   be no way to leave this room!.
A voice says: "Correct!"
There are doors in the west and south   walls.
=
003,Chute Room
   There are doors in the north & west
walls, and there is a chute leading up
in the south wall.
-
1,0,0,-33,0,0,0,0,0,0
The door is locked!
USE WAND,0,0
BOOK,first edition book,10,0
BOOK
It is an autographed first edition of   "The Fellowship of the Ring"!
CHUTE
Too steep to climb.
WEST DOOR
It radiates an aura of magic.


2
Fight magic with magic!
The west door is magically locked.
The west door opens.
The west door is open.
=
006,Parquette Hallway
   You are in a very wide north-south
hallway.  The floor seems to be
parquette.
-
-5,-7,0,0,0,0,0,0,6,6

SAY BUTTER,2,2
,,0,0
FLOOR
The parquette floor is making you dizzy.The patterns seem to form words.  There seems to be something very confusing    about it...





FLOOR
Tastes like...
2
Is the floor really parquette (sic)?
A strange voice says: "Parquette"
A feeling of confusion passes.
To the north you see a room with an old chandelier hanging from the ceiling. To the south is a very large room.
=
007,North End of Throne Room
    You are at the north end of a large throne room. A large green throne is to the south, and to the north is a par-
quette hallway. There is a large fis-
sure in the floor between you and the
throne.
+
   There are two rows of massive marble pillars holding up the arched ceiling.
Most of the pillars are intact, but one
-
6,-8,0,0,0,0,0,0,0,0
The fissure is too wide!
CLIMB PILLAR,0,2
,,0,0
FISSURE
The fissure is 12 feet wide. The bottom cannot be seen!
THRONE
It is too far away.




0

of the pillars is cracked and uneven    enough to climb.
You get halfway up when the pillar givesway. You fall 10 feet to the floor amid the falling debris. <<< OUCH! >>>
of the pillars has collapsed, forming a bridge across the fissure.
=
008,South End of Throne Room
   You are in a very large room with
a high arched ceiling supported by
massive marble pillars.  There is a
narrow passage to the east with steps
going down.
+
   There is a large jade throne near thesouth wall, facing you. There is a smallsign on the wall above the throne.
-
7,0,25,0,0,0,9,0,0,25

SIT,0,122
NECKLACE,pearl necklace,10,0
THRONE
The throne is solid jade, too heavy to  lift. There is a secret door next to thethrone leading south-east.




SIGN
Don't sit here!
2
Don't disbelieve everything you read.

You feel a strange and unpleasant sen-  sation. You become lethargic and drowsy,and soon you nod off to sleep........
...ZZZZZZZZZZZZZzzzzzzzzzz...
=
009,Secret Treasury Room
   You are in small room.  A passage
leads to the north-west.  Littering the floor are the remains of tables, chairs and other furniture.
+
   There is blood spattered over
everything, including the walls.  A few maggot-ridden corpses are lying in the
north-east corner of the room.
+
   All along the southern wall are largechests, but they have all been opened
and plundered. However, there's so much debris in the room that some treasure   may have been overlooked.
-
0,0,0,0,0,8,0,0,0,0

WAVE WAND,-100,0
GOLD,gold bar,10,1
DEBRIS
There is a gold bar here! (No, this     isn't Colossal Cave.)
BLOOD
It appears fresh!
CORPSE
The bodies are still warm!


0


The corpses start to move! They attack  you, and rip you into a million pieces!
You gave the ghouls indigestion.
=

