010,Steep Passage
   You are in steep passage going
down to the north-east. If you do go
down, you may not be able to get back
up without help.
-
0,0,0,0,-11,0,0,5,5,-11
The vicious dog won't let you!
USE SANDWICH,0,3
,,0,0








5
Maybe he's hungry?
There is a vicious dog blocking you!
The vicious dog grabs the sandwich and  quickly devours it. The dog is now ill.
There is a very sick dog here.
=
011,Debris Room
   There is a lot of debris here.
Passages lead north and south-west
from here.
-
12,0,0,0,0,0,0,-10,-10,0
It's too steep, you need help.
USE ROPE,0,3
ROPE,rope ladder,0,1
DEBRIS
Amid all this debris you find a rope    ladder!






0


There is a rope ladder permanently in-  stalled in the north passage.
There is a rope ladder permanently in-  stalled in the north passage.
=
012,Pool Room
   Here the passage widens and is
blocked by a deep pool.  Water drips
from a stalactite hanging down from the ceiling into the pool.  The pool over-
flows into a tunnel in the northern
wall.
-
0,11,0,0,0,0,0,0,0,0

SWIM,0,113
,,0,0
POOL
The pool looks deep, but the water      appears clean.






5
Can't you swim?

Brrrrr! The water is cold...The current is too strong, and you are carried by   the water into the forbidding-looking   tunnel!...
...Splash...
=
013,Stream Room
   A stream issues from a tunnel in the south wall.  The stream has cut a
shallow channel down the east side of   the room. It then exits the room
through a low tunnel in the north wall.
A passage exits to the west.
-
0,0,0,14,0,0,0,0,0,0

SWIM,0,115
,,0,0
STREAM
The stream is icy cold.






0


Brrr...The water is really cold!        You are carried into the tunnel, and    you pass out from the cold.....
...Splash...
=
014,Dead End
   The only exit is to the east.
-
0,0,13,0,0,0,0,0,0,0

GET PELVIS,-100,0
,,0,0
PELVIS
There seems to be a sickly green aura   surrounding it.






5
There is danger here, make no bones     about it!
In the south-west corner of the room is a human pelvis.
You touch it, & your hand turns leprous green. It spreads upwards & pieces of   skin slough off. As your face melts, youpass out...

You have died from the creeping crud.
=
015,Pit Room
   A stream issues from a tunnel in the south wall, and disappears into a large pit in the floor. There is a door in
the north wall.
-
17,0,0,0,0,0,0,0,0,-16
Don't be rash, you'll break your neck!  You need a rope.
USE ROPE,0,3
,,0,0
PIT
The pit is about 3 feet in diameter, andthe bottom is 20 feet down. There is a  strange glow at the bottom of the pit.






0


There is a rope ladder hanging down intothe pit.
There is a rope ladder hanging down intothe pit.
=
016,Diamond Room
   You are in a large room cut into
diamond rock.  Huge boulders of rough
diamond lie scattered on the floor. All of them are too big to lift.  There is
an inscription on the biggest boulder.
+
  There is a hole in the ceiling 12
feet overhead. There appears to be no
other exit.
-
0,0,0,0,0,0,0,0,-88,0
The rope ladder is 12 feet above you!
USE WAND,0,101
RING,diamond & sapphire ring,10,1
BOULDER
There is a diamond & sapphire ring on   top of the biggest boulder!
DIAMOND
The diamond boulders are too big to     lift!
BOULDER
The diamond boulders are too big to     move!


5
A magic wand might be useful here.

You wave the wand, & the diamond walls  glow brighter & brighter. You're blind!.Then, slowly, the light fades.....
...brightness...
=
017,Button Room
  There is a door in the south wall,
and a red button on the north wall.
There is a sign above the button.
-
0,15,0,0,0,0,0,0,0,0

PUSH BUTTON,0,121
,,0,0
BUTTON
The button is red.




SIGN
Push me.
0


<<< POOF! >>>  You are enveloped in a   cloud of acrid smoke.
<<< COUGH, COUGH >>>
=
018,Crystal Room
  The walls and ceiling of this room
are made of a translucent crystal sub-
stance.
-
0,0,-19,0,0,0,0,0,0,0
The glare is blinding!
SHIELD EYES,0,0
ORB,crystal orb,10,0








2
Shield your eyes.
The glare from the walls is blinding!
Much better!

=
019,Dusty Hall
   You are in a narrow hallway covered
with about three inches of dust. It is
obvious that very few adventurers have
come this way. There are a few tracks
heading west, but none returning!
+
   There is a passage to the east and a door to the west.  There is a plaque
above the west door.
-
0,0,5,-18,0,0,0,0,0,0
The troll is blocking your way!
USE DAGGER,2,2
,,0,0
TROLL
You can tell that the guard is an ex-   marine by the gill slits on his neck.




PLAQUE
Authorized personnel only!
0

There is a big burly troll gaurding the west door!
You killed him!
There is a big burly troll dead on the  floor.
=

