020,Endless Hall
   You are in a long, featureless,
east-west hallway.
-
0,0,21,1,0,0,0,0,0,0

,0,0
,,0,0
HALL
The hall is endless.






0




=
021,Endless Hall
   You are in a long, featureless,
east-west hallway.
-
0,0,22,-20,0,0,0,0,0,0
First, say please!
SAY PLEASE,-10,2
,,0,0
SIGN
The sign is glowing red, and is very,   very hot!
HALL
The hall is endless.


SIGN
You cannot return to the west unless yousay PLEASE. (The damage to your dignity will cost you 10 points.)
0

There is a sign floating in the air     to the west of you.
The sign fades away.

=
022,Endless Hall
   You are in a long, featureless,
east-west hallway.
-
0,0,23,21,0,0,0,0,0,0

,0,0
,,0,0
HALL
The hall is endless.






0




=
023,Endless Hall
   You are in a long, featureless,
east-west hallway.
-
0,0,24,22,0,0,0,0,0,0

EAT SANDWICH,-100,0
SANDWICH,moldy sandwich,0,0
HALL
The hall is endless.
SANDWICH
It is covered with slimy green mold!




0


Yeccchh! As you choke on the sandwich,  your face turns a livid green!
You have died of food poisoning!
=
024,Endless Hall
   You are in a long, featureless,
east-west hallway.
-
0,0,20,23,0,0,0,0,0,0

USE COMPUTER,0,0
COMPUTER,Model 100 computer,10,0
COMPUTER
The Model 100 is the best value for the money.
HALL
The hall is endless.




0


You are!

=
025,Room of Statues
   You are in a room that used to house and display sculpted statues. Most of
them have been destroyed, with  pieces
of them scattered about the floor.
Most of the shelves are empty.
There is a crack in the north wall.
-
26,0,0,8,0,0,0,0,8,0

RUB STATUE,0,101
STATUE,jade statue,10,1
SHELVES
On one shelf you see a jade statue of a beautiful princess. There is an inscrip-tion on its base.
SHELVES
The shelves are empty.
CRACK
The crack is just wide enough to slip   through.
INSCRIPTION
For a good time, rub me.
0


You rub the statue, & it starts to glow.You feel a tingling in your hand, and   there is a tremendous explosion!
<<< KABOOM! >>>
=
026,Narrow Crack
   The crack is blocked to the north
by rubble. To the south is a room.
-
-99,25,0,0,0,0,0,0,0,0
It is too narrow!
USE WAND,-100,0
RUBY,large red ruby,10,1
RUBBLE
There is a large red ruby buried in the rubble!






0


The walls rumble and shake, and then ra-pidly close in on you.
You are a victim of the Dungeon Diet.
=
027,Odd-shaped Room
   There are exits to the S, E, W & NW.
-
0,45,27,28,0,42,0,0,0,0

,0,0
,,0,0








0




=
028,Succubus Lair
   This room is furnished like a royal
bedroom, with an expensive-looking
dresser and a canopied four-post bed.
+
   Exits are to the S, E, W & NE.
-
0,44,27,41,42,0,0,-29,0,0

COVER SUCCUBUS,2,2
GOBLET,crystal goblet,10,0
BED
There is an inscription engraved on     the headboard.




INSCRIPTION
She who lies here protects the password from those who abuse what is not theirs.The password and her cannot be together exposed.
10
Re-cover what is exposed, and you will  uncover what is hidden.  Besides, its   cold in here.
There is a beautiful demon (Succubus)   sleeping on the bed.  She is lying face up and naked with the bedcover at her   feet.
You here a creaking sound and see a     secret panel open in the southwest      corner of the room.
There is a secret panel open in the     southwest corner of the room
=
029,Odd-shaped Room
   There is an exit to the SW.
-
0,0,0,0,-99,0,0,40,0,0
The door will not open from this side.
,0,0
KEY,small brass key,10,0








0




=

