030,Silver Room
   The walls of this room are plated
with silver, which you quickly discover cannot be removed.  There are various
pieces of furniture here, including a
large table made of solid silver.
+
   Against the north wall you see a
large chest also made of silver.  It is apparently empty.  There is a door in
the east wall, and a small circular
tunnel in the south wall.
-
0,31,2,0,0,0,0,0,0,0

,0,0
SLIVER,sliver of silver,10,1
CHEST
Well I'll be darned, it isn't empty.    The chest contains a sliver of silver!
CHEST
It's empty.
TABLE
The table is solid silver, and far too  heavy to carry.


5
Examine the chest, numbskull!



=
031,Fern Room
    You are in an underground tropical  garden.  Water sprinkles from the
ceiling onto the ferns that seem to
grow right out of the the stone floor.
It is very humid, and the walls and
floor are very damp.
+
There is a passage in the north wall.
-
30,-32,0,0,0,0,0,0,0,0
The tunnel is too small for you!
GET NOTHING,2,2
,,0,0
FERN
I hate to disappoint you, but the ferns are not edible.
GARDEN
Nothing is obtainable here!
WATER
NOTHING is more interesting!


2
Nothing is very useful in this room. Getit?
The water exits through a tiny tunnel   in the south wall. There is nothing     of value here.
Taken!
The water exits through a huge tunnel inthe south wall.
=
032,Slimy Tunnel
   You are in a narrow north-south
tunnel.  The walls are covered with a
strange slimy mold, and exude a
terrible stench.  Let's get out of
here quickly!
-
31,33,0,0,0,0,0,0,0,0

EXAMINE MOLD,-100,0
,,0,0








0


As you peer at the mold, it jumps out atyou! It covers your face, and enters    your nose and mouth. You can't breathe!
Asphyxiation is a terrible way to die.
=
033,Demon Lair
   You are in a small room that looks
like it has been lived in for 10,000
years, and that the occupant did not
know where the bathroom was.  Needless
to say, the stench is overpowering.
+
   There is a door in the east wall,
and a narrow tunnel exits to the north.
Refuse is piled against the south wall.
-
-32,-34,-3,0,0,0,0,0,0,0
The demon is blocking the way!
PUSH DEMON,2,2
SCABBARD,gem encrusted scabbard,10,0
REFUSE
Yeccch! What a mess!  There is a secret door in the south wall.






5
Demons are generally deranged. One mighteven say unstable.
There is a large, one-legged demon      here!
The demon falls over and drowns in his  own refuse!
There is a dead, decomposing demon      here.
=
034,Fog Room
   There is a lot of fog here.
-
33,-35,0,0,0,0,0,0,0,0
The fog is too thick to walk through!
USE WAND,0,0
DAGGER,fire dagger,10,1
FOG
There is a passage to the south, and a  glowing dagger on the floor!
FOG
There is a passage to the south.




2
The fog might be worth examining.
The fog is extremely thick.
The fog begins to thin considerably.

=
035,Rope Room
    The room is non-descript, except
for a passageway to the northeast, and
-
0,0,0,0,34,0,0,0,0,0

CLIMB ROPE,0,136
,,0,0
ROPE
The rope looks strong enough to support your weight.
HOLE
It is too dark to see anything.




0

the hole in the ceiling. Hanging down   through the hole is a rope.
You grab onto the rope, & something (or someone) pulls it up rapidly, taking youalong with it!
...speeding up through the hole...
=
036,Fries Room
   There is a passageway in the east
wall.
-
0,0,37,0,0,0,0,0,0,-99
Th hole isn't there anymore!
,0,0
CHIPS,bag of 80C85 microchips,10,1
FRIES
Chips, no fries. The chips are 80C85    CPUs wrapped in an anti-static bag.
FRIES
Fries, no chips.
CHIPS
They are 80C85 CMOS CPU chips as used inthe Model 100.


0

There are fries here.


=
037,Shooting Gallery
   This room is non-descript, except
for a passageway to the west and a leveron the east wall.
-
0,0,0,36,0,0,0,0,0,0

PULL LEVER,0,103
PLATINUM,bar of platinum,10,0
LEVER
The lever is made of wood and is paintedred.  There is a small sign above it.




SIGN
Pull this lever to shoot (sic).
0


As you pull the lever, the floor opens  under your feet, and you find yourself  sliding down a smooth chute into dark-  ness.....
...sliding down the chute...
=

