040,Circular Room
   You are in a large circular room 30  feet in diameter.  The ceiling is 20
feet above your head.  There is a human skeleton lying on the floor next to the western door.
+
   There are doors to the north, south, east and west. There is an inscription
on the western door.
-
41,43,45,-5,0,0,0,0,0,0
The door is locked!
USE KEY,2,2
,,0,0
SKELETON
From the condition of the skeleton it   appears that the person was trying to   beat the western door down with his     skull.
WEST DOOR
The western door is locked.


INSCRIPTION
The key is closer than you think, but   farther than you would hope. You must   search for it.
0

The western door is locked.
The western door swings open with a     groan!
The western door is open.
=
041,Odd-shaped Room
   There are exits to the NE and S.
-
0,43,0,0,42,0,0,0,0,0

,0,0
CREDIT CARD,credit card,10,0








0




=
042,Odd-shaped Room
   There are exits to the N, S & SW.
-
42,45,0,0,0,0,0,41,0,0

,0,0
,,0,0








0




=
043,Odd-shaped Room
   There are exits to the N, S & NE.
-
41,43,0,0,45,0,0,0,0,0

,0,0
,,0,0








0




=
044,Demon Lair
   From the filth and refuse scattered
on the floor, this must be a demon lair.The walls and ceiling are scorched as
from fire, and the air is very hot.
+
   There are exits to the N, NE and SW.
-
-42,0,0,0,-27,0,0,-43,0,0
The demon is blocking you!
SPIT,2,2
,,0,0








8
Fire demons hate ANY kind of water.
There is a giant Fire Demon menacing    you!  Run away...........
You hit it!  The Fire Demon sizzles and goes out, leaving behind only a sicken- ing smell!
The smell here is sickening, yeccch!
=
045,Odd-shaped Room
   There are exits to the N, S, and SW.
The western exit is blocked by rubble.
-
42,43,0,-44,0,0,0,43,0,0
You can't walk through rubble!
CRAWL,0,144
PAINTING,beautiful painting,10,0
PAINTING
It is a magnificent work of art!
RUBBLE
The rubble is from a recent cave-in. Youmay be able to crawl here.




0


As you crawl through the rubble it col- lapses behind you and blocks your re-   treat.
<<< Crumble, Crumble >>>
=

