NORSOUEASWESUP DOWSCOINVQUISTOENDGETTAKKEEREMSTEGRAPUTDRORELPLATHRREPMOVGO WALRUNJUMCLILOOEXAREABREASMADESHITKILATTFIGPUSPREDEPSAYYELSCROPEPRYCLOSHULOCUNLDRIEATRESSLELIGBURIGNFEECUTSLISCALIFRAISIT
NORSOUEASWESUP DOWRUGKEYLANLIGPOTPAILETGUNLIQTILRAGCROKNIFUSSACCOIWINPAPCOMCANPAICHOFOODOOTABCHASOFFIRSTASTOSHEDESLOCTRASINTUBCABBEDMATNIGGRASIGBUTNICGHOALLROOWALCEIFLOEVEINVBOO
a welcome rug,1
a brass key,-2
a fine kerosene lantern,-1
a butane lighter,6
pots and pans,6
paintings of venerable men,9
a letter,-2
some gunpowder,14
a smoky liquid,14
a loose floor tile,-2
a pile of rags,12
a crowbar,-2
a knife,-2
a piece of fuse,-2
a small cloth sack,-2
many gold coins,-2
a bottle of fine wine,22
a slip of paper,-2
an empty paint can,12
purina alligator chow,17
a large oaken door,1
a finely crafted table,8
several chairs,8
a large sofa,3
a stone fireplace,3
a spiral staircase,2
a cast iron stove,6
empty shelves,6
a large desk,10
*,-3
a trapdoor,11
a bathroom sink,19
a bathtub,19
a bathroom cabinet,19
a large bed,18
a matress on the bed,18
a nightstand,18
a metal grate,23
a large sign,16
a secret button,-2
a hidden niche,-2
a scary ghost,8
a hungry alligator,24
a rug
a key
a lantern
a lighter
some pots
some paintings
a letter
some gunpowder
smoky liquid
a loose tile
some rags
a crowbar
a knife
a fuse
a small sack
some coins
some wine
a slip of paper
an empty paint can
alligator food
out of the sewer! I won!
0,0,0,0,-1,-1
standing on the front porch
-1,-1,-1,-1,-1,-1
standing on a spiral staircase going up and down
-1,-1,-1,3,15,22
in the living room of the house
-1,7,-1,4,-1,-1
standing in the checkered foyer
1,8,3,5,-1,-1
in the beautiful sitting room
-1,9,4,-1,-1,-1
looking around in the kitchen
-1,11,-1,7,-1,-1
at the east end of the dining room
3,-1,6,8,-1,-1
in the middle section of the diningroom
4,-1,7,9,-1,-1
at the west end of the dining room
5,-1,8,10,-1,-1
standing in Harrow's study
-1,-1,9,-1,-1,-1
in the kitchen pantry
6,-1,-1,12,-1,-1
checking out the workshop
-1,-1,11,-1,-1,-1
in the red wallpapered guest bath
8,-1,-1,-1,-1,-1
in the secret laboratory..
10,-1,-1,-1,-1,-1
in the 2nd floor sitting room
-1,18,-1,16,-1,2
in the hallway outside the master  bedroom
-1,20,15,-1,-1,-1
observing the master bedroom
-1,21,16,-1,-1,-1
walking through a guest bedroom
15,-1,-1,19,-1,-1
in the bathroom
-1,-1,18,20,-1,-1
walking through a guest bedroom
16,-1,19,-1,-1,-1
in the giant, lavish master        bathroom
17,-1,-1,-1,-1,-1
in the cold wine cellar
-1,-1,-1,-1,2,-1
in the cellar
-1,-1,-1,-1,-1,-1
in the putrid, smelly sewer
-1,-1,23,-1,-1,-1
standing knee-deep in smelly sewer water
-1,-1,24,26,-1,-1
in a roughly carved passageway
-1,27,25,-1,-1,-1
in a large cavern hollowed out of  solid rock. A large movie screen is at one end.
26,-1,-1,-1,-1,-1
Ooh I feel lightheaded!
My stomach feels funny!
My head is spinning!
I can't think right!
I think that wine did something to me!
north,south,east,west,up,down
