     This is a brief text to explain how
to transfer files between the Apple 
computer with DC Hayes micromodem and 
terminal program and the Model 100.  
Obviously, with the two modems present, 
you don't need a null modem.  Transfer 
is only 300 baud, but it works easily.
     The two modems can be either jacked
together directly with the supplied 
double female modular coupler, or with 
one of the computers plugged into an 
extension phone jack.
     Set the 100 to "answer" (not 
"originate").  Use the Hayes terminal 
program to dial your own phone number.  
When the prompt on the Apple says 
"awaiting carrier", hit F4 (term 
function key), and both computers will 
now be "online" with each other.  Oddly 
enough, unless both computers are set to
half duplex, you will not see your text 
on both screens-only on the other 
machine!  This doesn't matter if left as
is; any program you want to transfer 
will still do so using the up- and 
download keys on the 100, or the 
"receive" or "send" commands in the 
terminal program in the Apple. 
    I have used this method to send text
files to the Apple for editing with 
Screenwriter II; this allows full page 
formatting before I then send it to the 
printer.  Also, if you wish to download 
many files from CIS and are concerned 
about running out of memory in the M100,
you can save a great deal of data to 
disk on the Apple, edit it at leisure, 
and then send the finished product to 
your M100.
     Although this sounds ridiculously 
easy, it works amazingly well.  I would 
think just about any other computer/
modem arrangement would work as well.  
