

MODEL 100 AND COMMODORE 64 "TALKING" WITHOUT THE USE OF TELEPHONE LINES

-----------
IT'S EASY!:
-----------

I am very new to computing.  I jumped into the world of computing with my 
Commodore 64 (C-64) in June, 1984, became a second computer owner (a Commodore 
SX-64 for work) that Fall, and got my Model 100 (M100) at Christmas '84.  I was
mystified by the idea of my M100 "talking" to my Commodores without the use of 
the telephone lines and modem, but I had read enough to know it could happen--
and easily.  I found out, much to my surprise, that sure enough, IT'S EASY!

Now I am merrily writing TEXT files on my M100 in the car or in my easy chair 
in front of the TV, and transferring them to my C-64 with very little effort.  
By learning how to make the two computers "talk" side by side, I have saved 
myself the cost of a monitor, disk drive, and printer for the M100 by using the
64's equipment.  I don't mind saving $1000-$1500, do you?!

-------------------------------------
WHAT HARDWARE AND SOFTWARE DO I NEED?
-------------------------------------

One major factor which scared me to death about the idea of hooking these two 
computers together was the hardware and software configuration I would need.  
Again, it's not as complicated as you may think.  Follow my directions, and 
you'll have the two machines "talking" in no time!

Here's the hardware and software you'll need:

     (1)  The Commodore VIC-1011-A RS-232 Cartridge [$59.95]:  This cartridge 
plugs into the USER PORT in the back of the C-64 (where the modem would 
normally go) in order to give the C-64 an RS-232 outlet.  It is available from 
most Commodore retail stores or directly from Commodore Business Machines, 
Ltd., 1200 Wilson Dr., West Chester, PA 19380.  [ASIDE:  Purchasing this 
cartridge will also allow you to use modems not normally thought of for use 
with the C-64 which require an RS-232 outlet, such as the Hayes Micromodems.]

     (2)  Radio Shack's RS-232 Cable, male to male [$19.95]:  This cable is 
readily available from all Radio Shack stores, and must have male connectors at
both ends.

     (3)  Radio Shack's Null Modem Adaptor [$29.95]:  Also readily available 
from Radio Shack stores.

     (4)  Terminal Software for the C-64 with UPLOAD/DOWNLOAD Capability:  I 
use VIP TERMINAL [$49.95] which is available from many stores selling Commodore
software or directly from Softlaw Corporation, 132 Aero Camino, Goleta, CA 
92117, (805) 968-4364.

-------------
HOW TO DO IT:
-------------

First, set the two computers side by side.  MAKE SURE BOTH COMPUTERS ARE OFF.  
I cannot emphasize this point enough.  Connecting any devices into the 64's 
User Port with the computer on will blow its insides to pieces.

Now, starting with the C-64, and moving toward the M100:

     (1)  Connect the 1011-A Cartridge into the 64's User Port.

     (2)  Connect the Null Modem Adapter to the 1011-A Cartridge.

     (3)  Connect one end of the RS-232 cable to the Null Modem Adaptor.

     (4)  Connect the other end of the RS-232 cable to the RS-232 port on the 
back of the M100.  That's the connection!  I told you it was EASY!

Now, turn on the 64's monitor, disk drive, and the C-64, and load your terminal
software.  Since I use VIP TERMINAL, I'll refer to it in what follows.  Set the
terminal parameters to 300 baud, Even parity, 1 stop bit, Half duplex, 
Linefeeds:Both, and FAST transmit speed.  Turn on your M100, go to TELCOM, and 
set STAT for 38N1E,10.

TO UPLOAD AN M100 FILE FROM THE 100 TO THE C-64:

Go to TALK in VIP Terminal, and open the workspace (press the Commodore key and
"w" at the same time).  Ignore the "Carrier Present" or "No Carrier" messages 
on the 64's monitor.  On your M100, press TERM [F4], select HALF duplex [F4], 
and UPLOAD [F3].  At the FILE TO UPLOAD? prompt, give the name of the TEXT file
(.DO is not necessary).  At the WIDTH? prompt, select "80" for an 80 column 
printout from the C-64.  Then hit ENTER on the M100.  On your M100, the word UP
will go into reverse video during the upload.  On your 64's monitor, you'll see
the file appearing on the screen as you are uploading.  When the M100 finishes 
the upload (the word UP goes from reverse to normal video), turn it off to save
the batteries.  Push F8 and "y" at the DISCONNECT prompt, push F8 to go back to
the main menu, then turn the M100 off.  On your C-64, close the workspace by 
pressing Commodore key and "w" simultaneously again.  Now go to the FILE 
MANAGEMENT menu in VIP TERMINAL.  You can now edit the workspace, print it, or 
save it to disk!  REMEMBER:  IF YOU DECIDE TO QUIT, TURN THE C-64 OFF BEFORE 
DISCONNECTING THE CARTRIDGE, CABLE, ETC.  YOU WILL DAMAGE YOUR "LIVE" COMMODORE
IF YOU DON'T TURN IT OFF FIRST!!!

TO DOWNLOAD A C-64 FILE FROM THE C-64 TO THE 100:

Just reverse the procedures, and it should work fine.

----------------------
OTHER HELPS AND HINTS:
----------------------

I keep my 1011-A Cartridge and Null Modem Adaptor rubber-banded together for 
quick connections.  Also, I keep the cartridge, null modem, and cable in a 
small case in my briefcase next to my M100 for use at home or work.

If you have any questions about these instructions, feel free to leave me a 
message on the M100 sig (go pcs 154) or the C-64 sig (go pcs 156):  John D. 
Bloodworth: CIS #75206,744.

--------------------------
HAPPY M100/C-64 "TALKING"!
--------------------------

