

SMART.SIG was the original, script-automated access program, written to
navigate through CompuServe's forums, read or download messages, prepare
replies offline, and upload them automatically.  It was no longer supported by
the original author, Howard Benner, who moved on to create TAPCIS, and who has
since passed away.

Scripted programs rely on CompuServe's "prompts" to operate, and each time the
system's prompts are changed, the program must be updated or adjusted to deal
with the new prompts.  CompuServe's software changes over the years have made
the original program obsolete.

There is a similar program currently available for the Tandy portables, called
EM8SIG, which is also in this library.  A SCAn of the title will list the
relevant files (SCA EM8SIG).  This program is also available, complete with
documentation and relevant files in an ARCed form which can be downloaded by PC
users, dearced, and loaded into their portables.  Originally written by Marvin
Miller (who has also passed away), it is currently supported on the forum
message board by Stan Wong, 70346,1267, and other active users.

