     CABLE.MOD    -----    Mike Audleman 73577, 3041  28 Apr 1989

        Tired of that just to short cable for  the  Mod  100  to  the  DVI?
     Can't get a disk in the lower drive without a  standby  contortionist?
     Well, if you can handle a small screwdriver and a  pair  of  scissors,
     you are in luck.

        Before we get started, there is one very important word of caution,
     this modification is NOT, and repeat NOT for the Model 102!  The cable
     that is provided with the DVI for the 102 is plenty  long  enough  and
     the connector for the system bus is on the back so there is no problem
     with length.

        The problem lies in that the cable for the 100  must  reach  almost
     the full depth of the 100 itself and then under the DVI.  This creates
     a problem with moving the 100 sideways, the cable lying under the  100
     must remain flat so that is virtually impossible without putting undue
     stress on the connector and the socket in the model 100.  The solution
     is a simple one, get a longer cable.  That is where money comes in and
     if you are on a tight budget, things like ribbon cable and  connectors
     are not in it.  Another solution, the one I will describe here, is one
     of using ON-HAND materials that are currently not being used (at least
     as far as the Mod 100 and DVI are concerned).  The ON-HAND materials I
     speak of is the DVI to Model 102 cable.  Yes, I know it looks like you
     can just plug it in because the connectors are  the  same.   BUT,  the
     problem is the Mod 102 cable does not mirror immage the Mod 100 cable.
     The way the Mod 102 cable is made, the top pins on the 100 cable  need
     to be connected to the bottom pins on the mod 100 cable.

     The fix is a VERY simple one, reverse the mod 102 cable pins from  top
     to bottom.  Believe it or not, this is extremely easy to do  and  only
     takes about 20 minutes to complete including testing.

        If you hold the Mod 102 cable up and look at it from the  side,  it
     should look like this:

     Figure 1.   Side View of the Original Tandy Supplied Cable.
            ____
           [____|  End for the Mod 102
                |
                |
                |
     Foil Side >|
                |
                |
                |
            ____|
           [____|  End for the DVI


       The plan of attack is to remove the connector from the  102  end  of
     the cable and re-connect it on the  OPPOSITE  side  (NOT  END!),  thus
     effectivly making all the bottom pins move to the top and the top ones
     move to the bottom.  After the modification,  the  cable  should  look
     like this:

     Figure 2.  Side View of the Modified Cable.

                       /- Notch in connector is on TOP
                 _____/
                |_____]    Previously then 102 end now for the Model 100
                |
                |
                |
     Foil Side -|
                |
                |
                |
            ____|
           [____|  End for the DVI


        To complete the  operation,  you  will  need  a  small  flat  blade
     screwdriver, a pair of pliers (not needlenose, the regular workin'  on
     the car type!) and a pair of scissors.  First the screwdriver must  be
     small enough to fit into the small rectangular hole in the  back  (the
     side away from the pins) of  the  connector  at  each  end.   A  small
     jewler's type will work perfectly.

        Step one.  GENTLY, GENTLY, pry the back piece  upward  and  remove.
     Set it aside.  Starting from one side, peel the ribbon cable away from
     the connector being very carefull not to dammage the tiny fingers that
     are imbedded in the cable from the connector. Start  at  one  end  and
     slowly work to the other.  Do not try to lift the  entire  cable  from
     the connector all at once!

        Step two.  Using the scissors, trim the end of the cable just  past
     the small puncture holes and remove them.  Try to cut as  straight  as
     you can.  Use a sharp pair, don't  use  the  school  house  kind.   If
     necessary, peel the foil ground shield back and trim the  ground  wire
     and foil  so  that  it  is  out  of  the  way  when  re-attaching  the
     connector.

        Step three.  Place the connector on a level  surface  facing  down,
     with the small fingers that connect to the cable facing up.  With  the
     notch in the connector facing away from you, place the cable on top of
     the connector with the DVI end tword you.  Replace  the  backpiece  of
     the connector and press firmly down with both thumbs just off centers.
     Don't  try  to  force  it  all  the  way  down  yet.   Pick   up   the
     connector/cable and look at it from unterneath.  It should  look  like
     this:

     Figure 3.  End View of the Connector and Ribbon Cable.

        /-Foil side of cable is on the back of the connector
    ___/______________  <-Back of connector
   |oooooooooooooooooo| <-Ribbon cable
   |VvVvVvVvVvVvVvVvVv| <-Note the fingers are centered arround each wire.
      ^-Top Finger ^-Bottom Finger

       If the cable and fingers do not line up, stop  and  re-position  the
     cable until they do.  If you proceed with the  cable  misaligned,  you
     WILL dammage the connector and/or render it  useless.   Once  you  are
     sure the connector and cable are properly aligned, plug the  connector
     into the end of the 100 cable  and  use  the  pliers  to  squeeze  the
     backpiece down forcing the fingers into the cable to make contact.  Do
     not sqeeze so hard that you dammage the connector but be very firm  to
     ensure that the fingers are seated well.

        This complets the modification, the cables are connected  togather.
     The end that did to go to the DVI is inserted into the modified  cable
     and it's end is then connected to the DVI. With this  cable,  you  can
     offset the Mod 100 from the front of the DVI or leave plenty  of  room
     between them for anything you  should  desire!   One  last  note,  you
     should make a lable (masking tape will  work)  and  place  it  on  the
     modified cable stating that it is modified and is not for use with the
     Model 102.

       Should you wish to return the cable to it's  original  form,  simply
     repeat the process and re-attach the connector so that the cable  once
     again looks like Figure 1.  I have  modified several cables  including
     mine with no problems at all.

        When they are all laid out, the cables should look  something  like
     figure 4.  If they don't, you have  made a mistake, go back  and  read
     the directions  carefully.  Short of dammaging  the  connector,  there
     isn't much you can do that can't be fixed.  It is ok to trim the cable
     more than once, just don't go overboard, preserve as much of the it as
     you can.

     Figure 4.  The Finished Cable Setup.

          /- Connector to Mod 100
         /                 /- Cable to Cable Connection
        /                 /_________________________|| <- To DVI
     |____|______________||           \
              \                        \-Modified 102 cable now for 100
               \-Original Mod 100 Cable remains unchanged.
